site_name: EVAdb
site_description: EVAdb - Exome Variant Analysis database documentation

repo_name: EVAdb Docs
repo_url: https://github.com/brand-fabian/evadb-docs
edit_url: 'edit/master/bih-cluster/docs/'

theme:
  name: material
  palette:
    scheme: slate
    primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.keys
  - def_list
  - attr_list

nav:
  - Home: index.md
  - Software Architecture: architecture.md
  - Installation:
    - Overview: installation/index.md
    - Docker:
      - Prerequisites: installation/docker/prerequisites.md
      - Download: installation/docker/download.md
      - Configuration: installation/docker/configuration.md
      - Build: installation/docker/build.md
      - First Start: installation/docker/run.md
    - Native Installation:
      - Installation: installation/native/index.md
  - Administration Guide:
    - Quick Start: administration/quick-start.md
    - Sample Management: administration/sample.md
    - Variant Annotation and Upload: administration/annotation.md
    - User Management: administration/user.md
    - Diseases and Disease Groups: administration/disease.md
    - Projects and Cooperations: administration/projects.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tables.js
  - js/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css