site_name: EVAdb
site_description: EVAdb - Exome Variant Analysis database documentation

repo_name: EVAdb Docs
repo_url: https://github.com/brand-fabian/evadb-docs
edit_url: 'edit/master/bih-cluster/docs/'

theme: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - def_list
  - attr_list

nav:
  - Home: index.md
  - Software Architecture: architecture.md
  - Installation:
    - Docker:
      - Prerequisites: installation/docker/prerequisites.md
      - Download: installation/docker/download.md
      - Configuration: installation/docker/configuration.md
      - Build: installation/docker/build.md
      - First Start: installation/docker/run.md
    - Native Installation:
      - Installation: installation/native/index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tables.js
  - js/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css